name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install and test
        run: |
          cd front-end
          yarn install
          yarn test:ci
      - name: Cypress tests (e2e) and endpoint
        run: |
          docker-compose up -d
          cd front-end
          yarn start & npx wait-on http://127.0.0.1:3000
          cd ../server
          yarn start & npx wait-on http://127.0.0.1:4000
          cd ../
          npx cypress run

